name: build

on:
  push

jobs:
  containerize:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t jonny7/binary:1.0.0 --build-arg COMMIT_HASH=${{ github.sha }} .

      - name: Run image
        run: |
          docker run jonny7/binary:1.0.0